#!/usr/bin/env python

def main_program(inputlist):
    board = ["1", "2", "3", "4", "5", "6", "7", "8", "9"]
    mark= "X"
    count =0
    for i in range(len(inputlist)):
        board[inputlist[i]-1]= mark
        mark= ("O" if mark=="X" else "X")
        count+=1
        if check_pattern(board):
            return count
        if count==9:
            return 0

def check_pattern(board):
    if check_diagonal(board) or check_horizontal(board) or check_vertical(board):
        return True
    return False

def check_horizontal(board):
    if board[0]== board[1] and board[1]== board[2]:
        return True
    elif board[3]== board[4] and board[4]== board[5]:
        return True
    elif board[6] == board[7] and board[7] == board[8]:
        return True
    return False

def check_vertical(board):
    if board[0]== board[3] and board[3]== board[6]:
        return True
    elif board[1]== board[4] and board[4]== board[7]:
        return True
    elif board[2]== board[5] and board[5]== board[8]:
        return True
    return False

def check_diagonal(board):
     if board[0]== board[4] and board[4]== board[8]:
        return True
     elif board[2]== board[4] and board[4]== board[6]:
        return True
     return False

inputnum= int(input().strip())
outputlist=[]
for i in range(inputnum):
    inputlist = input().split()
    inputlist= [int(i) for i in inputlist]
    outputlist.append(main_program(inputlist))

print(*outputlist)
