#!/usr/bin/env python
inputnum= int(input().strip())
inputlist= input().split()
inputlist= [int(i) for i in inputlist]
#
seed= 113
modulo= 10000007
result=0
for i in inputlist:
    result= (result+i) * seed
    result = result%modulo
        
print(str(result))
