#!/usr/bin/env python
inputnum = int(input().strip())
output = ""
for i in range(inputnum):
    r= 1
    inputlist = input().split()
    inputlist = [int(i) for i in inputlist]
    X= inputlist[0]
    N= inputlist[1]
    while N>0:
        r= (r+X/r)/2
        N-=1
    output+=str(r)+" "
    
print(output.strip())
