#!/usr/bin/env python
inputnum= int(input().strip())
output=""
for i in range(inputnum):
    inputlist = input().split()
    inputlist= [int(i) for i in inputlist]
    slope = (inputlist[1]-inputlist[3])/ (inputlist[0]-inputlist[2])
    intercept= inputlist[1] - (slope*inputlist[0])
    output+= "({} {}) ".format(int(slope),int(intercept))

print(output)
