#!/usr/bin/env python
inputnum= int(input().strip())
inputlist= input().split()
output= ""
#inputlist= [int(i) for i in inputlist]
for element in inputlist:
    weighted_sum=0
    num_list= [int(i) for i in list(element)]
    for index in range(len(num_list)):
        weighted_sum+= num_list[index] * (index+1)
    output+= str(weighted_sum)+" "

print(output.strip())
    
