#!/usr/bin/env python
inputnum = int(input().strip())
output = ""
for i in range(inputnum):
    count=0
    current=0
    inputlist = input().split()
    inputlist = [int(i) for i in inputlist]
    while count<inputlist[4]:
        current= inputlist[3]
        current = (inputlist[0] * current + inputlist[1]) % inputlist[2]
        inputlist[3]= current
        count+=1
    output+= str(inputlist[3])+ " "
print(output.strip())
