#!/usr/bin/env python
inputnum= int(input().strip())
output=""
for i in range(inputnum):
    inputlist= input().split()
    k = int(inputlist[0])
    sentence= inputlist[1]
    for i in range(len(sentence)):
        if k==0:
            break
        if k>0:
            sentence+=sentence[i]
            k-=1
        elif k<0:
            sentence= sentence[len(sentence)-i-1]+sentence
            k+=1
    output+= (sentence[int(inputlist[0]):] if int(inputlist[0])>0 else sentence[:len(inputlist[1])]) +" "

print(output.strip())
