#!/usr/bin/env python
num= input()
inputlist = input().split()
inputlist = [int(i) for i in inputlist]
next_num=0
output=""
for num in inputlist:
    step=0
    next_num=num
    while True:
        if next_num%2 == 0:
            next_num= next_num/2
        else:
            next_num= 3* next_num + 1
        step +=1
        if next_num ==1:
            break
    output+= str(step) + " "
    
print(output)
    
