#!/usr/bin/env python

inputnum= int(input().strip())
#
i=1
output=""
while i<=inputnum:
    in_pair=input().split()
    output+= str(int(in_pair[0])+int(in_pair[1])) + " "
    i+=1

print(output.strip())
