#!/usr/bin/env python

def convert_temp(celcius):
    result= round(((celcius-32) *(5/9)),2)+0.01
    result= round(result)
    return result

inputlist= input().split()
inputlist= [int(i) for i in inputlist]
output=""
for i in range(1,len(inputlist)):
    output += str(convert_temp(inputlist[i]))+ " "

print(output.strip())
