#!/usr/bin/env python
inputnum = int(input().strip())
output = ""
for i in range(inputnum):
    inputlist = input().split()
    inputlist = [int(i) for i in inputlist]
    S= inputlist[0]
    A= inputlist[1]
    B = inputlist[2]
    time = S /(A+B)
    output += str((time*A)) + " "
print(output.strip())
