#!/usr/bin/env python

inputnum= int(input().strip())
#
i=1
output=""
while i<=inputnum:
    inputlist= input().split()
    inputlist= [int(i) for i in inputlist]
    output+= str(min(inputlist))+" "
    i+=1
    
print(output.strip())
