#!/usr/bin/env python
inputnum= input()
inputlist = input().split()
inputlist = [int(i) for i in inputlist]
output=""
for num in inputlist:
    count=0
    temp=num
    matched= False
    temp_list=[str(num).rjust(8,'0')]
    while not matched:
        count+=1
        temp= temp**2
        temp_str= str((temp//100)%10000)
        temp_str= temp_str.rjust(8,'0')
        if temp_str in temp_list:
            matched= True
            continue
        temp_list.append(temp_str)
        temp = int(temp_str)
    output+= str(count)+" "

print(output.strip())
